name: device_chat_data
description: The project contains all the necessary repositories and services to make the application work
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  hive: ^2.2.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  crypto: ^3.0.6
  path: ^1.9.1
  hive_generator:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner:
  freezed: ^2.5.7
  json_serializable: ^6.9.0
